### List Products
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6ImFkbV8xenhXa2NrMURnTlM3M0JXX2xITjEiLCJpYXQiOjE3NjQwNzk5NjgsImV4cCI6MTc2NDA4MDAyOH0.BfuEkHaECBfa6bSjkBnq4OnZHxfWCLJYYiaOlGZLMuw

### Create product
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6ImFkbV8xenhXa2NrMURnTlM3M0JXX2xITjEiLCJpYXQiOjE3NjQwNzk5NjgsImV4cCI6MTc2NDA4MDAyOH0.BfuEkHaECBfa6bSjkBnq4OnZHxfWCLJYYiaOlGZLMuw

{
    "name": "Batom",
    "description": "Maquiagem para os lábios",
    "category": "Maquiagem",
    "supplier_id": "6912737ffb534981300b1d7c",
    "cost": 20,
    "price": 25,
    "inventory_quantity": 5
}

### Update Product
PATCH http://localhost:3000/products/prod_vZIePqDfihhiikV3kaR4b
Content-Type: application/json

{
    "inventory_quantity": 3
}

### Get Product by Id
GET http://localhost:3000/products/prod_vZIePqDfihhiikV3kaR4b

### Delete Product
DELETE http://localhost:3000/products/prod_vZIePqDfihhiikV3kaR4b